DROP TABLE IF EXISTS teams CASCADE;

CREATE TABLE teams (
    year_id INTEGER,
    lg_id VARCHAR(10),
    team_id VARCHAR(3),
    franch_id VARCHAR(3),
    div_id VARCHAR(1),
    rank INTEGER,
    g INTEGER,
    ghome INTEGER,
    w INTEGER,
    l INTEGER,
    div_win VARCHAR(1),
    wc_win VARCHAR(1),
    lg_win VARCHAR(1),
    ws_win VARCHAR(1),
    r INTEGER,
    ab INTEGER,
    h INTEGER,
    doubles INTEGER,
    triples INTEGER,
    hr INTEGER,
    bb INTEGER,
    so INTEGER,
    sb INTEGER,
    cs INTEGER,
    hbp INTEGER,
    sf INTEGER,
    ra INTEGER,
    er INTEGER,
    era DECIMAL(5, 2),
    cg INTEGER,
    sho INTEGER,
    sv INTEGER,
    ipouts INTEGER,
    ha INTEGER,
    hra INTEGER,
    bba INTEGER,
    soa INTEGER,
    e INTEGER,
    dp INTEGER,
    fp DECIMAL(5, 3),
    name VARCHAR(50),
    park VARCHAR(200),
    attendance INTEGER,
    bpf INTEGER,
    ppf INTEGER,
    team_id_br VARCHAR(3),
    team_id_lahman45 VARCHAR(3),
    team_id_retro VARCHAR(3),
    PRIMARY KEY (year_id, team_id)
);

CREATE INDEX idx_teams_year ON teams(year_id);
CREATE INDEX idx_teams_name ON teams(name);
CREATE INDEX idx_teams_franchise ON teams(franch_id);